apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment.yaml
- service.yaml

images:
- name: goserver
  newName: gutsmedeiros/gitops
  newTag: fd58f73e9e0c6ae6e4fb025ca093ffd4f8ba1983
