name: gitops
on:
  push:
    branches:
      - main

jobs:
  check-application:
    name: check-application
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build e Push da imagem
        id: docker_build
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: gutsmedeiros/gitops:latest